# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Partido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circunscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voto_partido_circu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votos', models.IntegerField(default=0)),
                ('circunscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Circunscripcion.Circunscripcion')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Partido.Partido')),
            ],
        ),
        migrations.AddField(
            model_name='circunscripcion',
            name='partido',
            field=models.ManyToManyField(through='Circunscripcion.Voto_partido_circu', to='Partido.Partido'),
        ),
    ]
