# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 11:27
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Circunscripcion', '__first__'),
        ('auth', '0008_alter_user_username_max_length'),
        ('Partido', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('DNI', models.CharField(max_length=9, unique=True)),
                ('ciudad', models.CharField(max_length=200)),
                ('codigoPostal', models.IntegerField()),
                ('mesa', models.CharField(max_length=200)),
                ('votado', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('ciudadano_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Ciudadano.Ciudadano')),
                ('imagen', models.CharField(max_length=200)),
                ('partido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to='Partido.Partido')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('Ciudadano.ciudadano',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='circunscripcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Circunscripcion.Circunscripcion'),
        ),
    ]
