# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('anioCreacion', models.IntegerField()),
                ('breveHistoria', models.CharField(max_length=600)),
                ('programaElectoral', models.CharField(max_length=1000)),
                ('imagen', models.CharField(max_length=200)),
            ],
        ),
    ]
